### ISSUE TITLE
0 triggers synced in dockerized Postegres

### ISSUE THREAD

**Issue by JestemStefan** [eviltnan/django-plpy#3]
Hi!

I'm trying to implement you library into my project.

I have two containers: one with my django app on ubuntu container and second with Postgres database on alpine-linux container.

I was able to set up everything until this point, but when I run `python manage.py syncfunctions` i get:
`Synced 4 functions and 0 triggers`

my trigger function looks basiacally like:
```
@pltrigger(event="INSERT", when="AFTER", model=Book)
def update_books_after_insert(
    new: Book, old: Book, td, plpy):
    # code code code
```

`manage.py checkenv ` shows that python versions match.

Can you give me some pointers what should I do so pltrigger is detected? Thank you

**Comment by thorin-schiffer** [comment]
Could you post your docker-compose file?
